"""vehicles staff crews documents

Revision ID: 4c1ecd74e054
Revises: 0002
Create Date: 2026-10-02 07:55:12.993561

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | Sequence[str] | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('lessor', 'lender', 'lessee', name='partykind', native_enum=False, length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('kra_pin', sa.String(length=20), nullable=True),
    sa.Column('payment_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_business_id'), 'parties', ['business_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('capacity_tonnes', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fuel_type', sa.Enum('diesel', 'petrol', name='fueltype', native_enum=False, length=30), nullable=False),
    sa.Column('tank_litres', sa.Integer(), nullable=True),
    sa.Column('expected_kmpl_loaded', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_kmpl_empty', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('tracking_tier', sa.Enum('basic', 'standard', 'premium', name='trackingtier', native_enum=False, length=30), nullable=False),
    sa.Column('depot_id', sa.Uuid(), nullable=True),
    sa.Column('ownership_type', sa.Enum('owned', 'asset_financed', 'leased_in', 'leased_out', name='ownershiptype', native_enum=False, length=30), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=True),
    sa.Column('gvw_limit_kg', sa.Integer(), nullable=True),
    sa.Column('axle_config', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'registration')
    )
    op.create_index(op.f('ix_vehicles_business_id'), 'vehicles', ['business_id'], unique=False)
    op.create_table('compliance_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.Enum('insurance', 'inspection', 'ntsa_licence', 'tlb_licence', 'permit', 'driving_licence', 'other', name='compliancedoctype', native_enum=False, length=30), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_documents_business_id'), 'compliance_documents', ['business_id'], unique=False)
    op.create_index(op.f('ix_compliance_documents_expires_on'), 'compliance_documents', ['expires_on'], unique=False)
    op.create_index(op.f('ix_compliance_documents_membership_id'), 'compliance_documents', ['membership_id'], unique=False)
    op.create_index(op.f('ix_compliance_documents_vehicle_id'), 'compliance_documents', ['vehicle_id'], unique=False)
    op.create_table('crew_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('driver', 'turnboy', name='crewrole', native_enum=False, length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_assignments_business_id'), 'crew_assignments', ['business_id'], unique=False)
    op.create_index(op.f('ix_crew_assignments_membership_id'), 'crew_assignments', ['membership_id'], unique=False)
    op.create_index('uq_crew_active_slot', 'crew_assignments', ['vehicle_id', 'role'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_index('uq_crew_active_person', 'crew_assignments', ['membership_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_index(op.f('ix_crew_assignments_vehicle_id'), 'crew_assignments', ['vehicle_id'], unique=False)
    op.create_table('staff_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('licence_number', sa.String(length=40), nullable=True),
    sa.Column('licence_class', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('monthly_salary_cents', sa.BigInteger(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id')
    )
    op.create_index(op.f('ix_staff_profiles_business_id'), 'staff_profiles', ['business_id'], unique=False)
    op.create_table('document_reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['compliance_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'expires_on', 'days_before')
    )
    op.create_index(op.f('ix_document_reminders_business_id'), 'document_reminders', ['business_id'], unique=False)
    op.create_index(op.f('ix_document_reminders_document_id'), 'document_reminders', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_reminders_document_id'), table_name='document_reminders')
    op.drop_index(op.f('ix_document_reminders_business_id'), table_name='document_reminders')
    op.drop_table('document_reminders')
    op.drop_index(op.f('ix_staff_profiles_business_id'), table_name='staff_profiles')
    op.drop_table('staff_profiles')
    op.drop_index(op.f('ix_crew_assignments_vehicle_id'), table_name='crew_assignments')
    op.drop_index(op.f('ix_crew_assignments_membership_id'), table_name='crew_assignments')
    op.drop_index(op.f('ix_crew_assignments_business_id'), table_name='crew_assignments')
    op.drop_table('crew_assignments')
    op.drop_index(op.f('ix_compliance_documents_vehicle_id'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_membership_id'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_expires_on'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_business_id'), table_name='compliance_documents')
    op.drop_table('compliance_documents')
    op.drop_index(op.f('ix_vehicles_business_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_parties_business_id'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
