"""sms two step

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 09:18:02.951556

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_challenges', sa.Column('purpose', sa.String(length=20), server_default='login', nullable=False))
    op.add_column('users', sa.Column('sms_2fa_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_2fa_enabled')
    op.drop_column('otp_challenges', 'purpose')
    # ### end Alembic commands ###
