"""photos inspections trips

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 09:37:34.878754

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: str | Sequence[str] | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('photo_on_fault', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_business_id'), 'checklist_items', ['business_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('odometer', 'cargo', 'defect', name='photokind', native_enum=False, length=30), nullable=False),
    sa.Column('source', sa.Enum('camera', 'web', name='photosource', native_enum=False, length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'sha256'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_photos_business_id'), 'photos', ['business_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('inspector_user_id', sa.Uuid(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'passed_with_defects', 'blocked', 'overridden', name='inspectionstatus', native_enum=False, length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['overridden_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_business_id'), 'inspections', ['business_id'], unique=False)
    op.create_index(op.f('ix_inspections_local_date'), 'inspections', ['local_date'], unique=False)
    op.create_index(op.f('ix_inspections_vehicle_id'), 'inspections', ['vehicle_id'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_business_id'), 'defects', ['business_id'], unique=False)
    op.create_index(op.f('ix_defects_inspection_id'), 'defects', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_defects_vehicle_id'), 'defects', ['vehicle_id'], unique=False)
    op.create_table('inspection_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_results_business_id'), 'inspection_results', ['business_id'], unique=False)
    op.create_index(op.f('ix_inspection_results_inspection_id'), 'inspection_results', ['inspection_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('driver_membership_id', sa.Uuid(), nullable=True),
    sa.Column('turnboy_membership_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'delivered', 'completed', 'cancelled', name='tripstatus', native_enum=False, length=30), nullable=False),
    sa.Column('cargo_description', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=160), nullable=True),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cargo_photo_id', sa.Uuid(), nullable=True),
    sa.Column('loaded_weight_kg', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_km', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cargo_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turnboy_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_business_id'), 'trips', ['business_id'], unique=False)
    op.create_index(op.f('ix_trips_driver_membership_id'), 'trips', ['driver_membership_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('odometer_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.Enum('start', 'end', name='readingphase', native_enum=False, length=30), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('auto_read_value', sa.Integer(), nullable=True),
    sa.Column('confirmed_value', sa.Integer(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'phase')
    )
    op.create_index(op.f('ix_odometer_readings_business_id'), 'odometer_readings', ['business_id'], unique=False)
    op.create_index(op.f('ix_odometer_readings_trip_id'), 'odometer_readings', ['trip_id'], unique=False)
    op.create_index(op.f('ix_odometer_readings_vehicle_id'), 'odometer_readings', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odometer_readings_vehicle_id'), table_name='odometer_readings')
    op.drop_index(op.f('ix_odometer_readings_trip_id'), table_name='odometer_readings')
    op.drop_index(op.f('ix_odometer_readings_business_id'), table_name='odometer_readings')
    op.drop_table('odometer_readings')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_membership_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_business_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_inspection_results_inspection_id'), table_name='inspection_results')
    op.drop_index(op.f('ix_inspection_results_business_id'), table_name='inspection_results')
    op.drop_table('inspection_results')
    op.drop_index(op.f('ix_defects_vehicle_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_inspection_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_business_id'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_inspections_vehicle_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_local_date'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_business_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_photos_business_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_checklist_items_business_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    # ### end Alembic commands ###
