"""fuel floats sync device

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-02 11:51:45.777152

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: str | Sequence[str] | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'client_id')
    )
    op.create_index(op.f('ix_sync_receipts_business_id'), 'sync_receipts', ['business_id'], unique=False)
    op.create_table('device_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clock_offset_s', sa.Integer(), nullable=True),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_checks_business_id'), 'device_checks', ['business_id'], unique=False)
    op.create_index(op.f('ix_device_checks_reported_at'), 'device_checks', ['reported_at'], unique=False)
    op.create_index(op.f('ix_device_checks_user_id'), 'device_checks', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_checks_vehicle_id'), 'device_checks', ['vehicle_id'], unique=False)
    op.create_table('float_transfers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_membership_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('mpesa_code', sa.String(length=12), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'mpesa_code')
    )
    op.create_index(op.f('ix_float_transfers_business_id'), 'float_transfers', ['business_id'], unique=False)
    op.create_index(op.f('ix_float_transfers_driver_membership_id'), 'float_transfers', ['driver_membership_id'], unique=False)
    op.create_table('fuel_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('litres', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('price_per_litre_cents', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('station', sa.String(length=120), nullable=True),
    sa.Column('mpesa_code', sa.String(length=12), nullable=True),
    sa.Column('receipt_photo_id', sa.Uuid(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'client_id'),
    sa.UniqueConstraint('business_id', 'mpesa_code')
    )
    op.create_index(op.f('ix_fuel_entries_business_id'), 'fuel_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_trip_id'), 'fuel_entries', ['trip_id'], unique=False)
    op.create_index(op.f('ix_fuel_entries_vehicle_id'), 'fuel_entries', ['vehicle_id'], unique=False)
    op.add_column('photos', sa.Column('client_id', sa.Uuid(), nullable=True))
    op.add_column('photos', sa.Column('late', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_photos_client_id'), 'photos', ['client_id'], unique=False)
    op.create_unique_constraint('uq_photos_business_client', 'photos', ['business_id', 'client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_photos_business_client', 'photos', type_='unique')
    op.drop_index(op.f('ix_photos_client_id'), table_name='photos')
    op.drop_column('photos', 'late')
    op.drop_column('photos', 'client_id')
    op.drop_index(op.f('ix_fuel_entries_vehicle_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_trip_id'), table_name='fuel_entries')
    op.drop_index(op.f('ix_fuel_entries_business_id'), table_name='fuel_entries')
    op.drop_table('fuel_entries')
    op.drop_index(op.f('ix_float_transfers_driver_membership_id'), table_name='float_transfers')
    op.drop_index(op.f('ix_float_transfers_business_id'), table_name='float_transfers')
    op.drop_table('float_transfers')
    op.drop_index(op.f('ix_device_checks_vehicle_id'), table_name='device_checks')
    op.drop_index(op.f('ix_device_checks_user_id'), table_name='device_checks')
    op.drop_index(op.f('ix_device_checks_reported_at'), table_name='device_checks')
    op.drop_index(op.f('ix_device_checks_business_id'), table_name='device_checks')
    op.drop_table('device_checks')
    op.drop_index(op.f('ix_sync_receipts_business_id'), table_name='sync_receipts')
    op.drop_table('sync_receipts')
    # ### end Alembic commands ###
