"""expenses reconciliation service work orders

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-02 12:35:46.297756

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: str | Sequence[str] | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('every_km', sa.Integer(), nullable=True),
    sa.Column('every_months', sa.Integer(), nullable=True),
    sa.Column('last_done_km', sa.Integer(), nullable=False),
    sa.Column('last_done_on', sa.Date(), nullable=True),
    sa.Column('advance_km', sa.Integer(), nullable=False),
    sa.Column('advance_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_schedules_business_id'), 'service_schedules', ['business_id'], unique=False)
    op.create_index(op.f('ix_service_schedules_vehicle_id'), 'service_schedules', ['vehicle_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('defect', 'service', 'manual', name='workordersource', native_enum=False, length=30), nullable=False),
    sa.Column('defect_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('urgent', 'high', 'normal', 'low', name='priority', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'waiting_parts', 'done', 'cancelled', name='workorderstatus', native_enum=False, length=30), nullable=False),
    sa.Column('assignee_kind', sa.String(length=20), nullable=True),
    sa.Column('assignee_name', sa.String(length=160), nullable=True),
    sa.Column('labour_cents', sa.BigInteger(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['service_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_business_id'), 'work_orders', ['business_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_vehicle_id'), 'work_orders', ['vehicle_id'], unique=False)
    op.create_table('route_costs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('category', sa.Enum('toll', 'parking', 'food', 'loading', 'police_county', 'repair', 'tyres', 'insurance', 'licence', 'permit', 'garage', 'service', 'overhead', 'other', name='expensecategory', native_enum=False, length=30), nullable=False),
    sa.Column('usual_cents', sa.BigInteger(), nullable=False),
    sa.Column('tolerance_pct', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_costs_business_id'), 'route_costs', ['business_id'], unique=False)
    op.create_table('spend_limits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('toll', 'parking', 'food', 'loading', 'police_county', 'repair', 'tyres', 'insurance', 'licence', 'permit', 'garage', 'service', 'overhead', 'other', name='expensecategory', native_enum=False, length=30), nullable=True),
    sa.Column('role', sa.Enum('owner', 'manager', 'supervisor', 'accountant', 'driver', 'turnboy', 'workshop', 'lessor', name='role', native_enum=False, length=30), nullable=True),
    sa.Column('limit_cents', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spend_limits_business_id'), 'spend_limits', ['business_id'], unique=False)
    op.create_table('work_order_parts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_parts_business_id'), 'work_order_parts', ['business_id'], unique=False)
    op.create_index(op.f('ix_work_order_parts_work_order_id'), 'work_order_parts', ['work_order_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_membership_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('opening_cents', sa.BigInteger(), nullable=False),
    sa.Column('floats_cents', sa.BigInteger(), nullable=False),
    sa.Column('expenses_cents', sa.BigInteger(), nullable=False),
    sa.Column('closing_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'approved', 'rejected', name='reconciliationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('balance_action', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'driver_membership_id', 'day')
    )
    op.create_index(op.f('ix_reconciliations_business_id'), 'reconciliations', ['business_id'], unique=False)
    op.create_index(op.f('ix_reconciliations_day'), 'reconciliations', ['day'], unique=False)
    op.create_index(op.f('ix_reconciliations_driver_membership_id'), 'reconciliations', ['driver_membership_id'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('done_on', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['service_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_business_id'), 'service_records', ['business_id'], unique=False)
    op.create_index(op.f('ix_service_records_vehicle_id'), 'service_records', ['vehicle_id'], unique=False)
    op.create_table('service_reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('due_key', sa.String(length=60), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['service_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'due_key')
    )
    op.create_index(op.f('ix_service_reminders_business_id'), 'service_reminders', ['business_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('driver_membership_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('toll', 'parking', 'food', 'loading', 'police_county', 'repair', 'tyres', 'insurance', 'licence', 'permit', 'garage', 'service', 'overhead', 'other', name='expensecategory', native_enum=False, length=30), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('mpesa_code', sa.String(length=12), nullable=True),
    sa.Column('receipt_photo_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('recorded', 'awaiting_approval', 'approved', 'rejected', name='expensestatus', native_enum=False, length=30), nullable=False),
    sa.Column('from_float', sa.Boolean(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('spent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'client_id'),
    sa.UniqueConstraint('business_id', 'mpesa_code')
    )
    op.create_index(op.f('ix_expenses_business_id'), 'expenses', ['business_id'], unique=False)
    op.create_index(op.f('ix_expenses_driver_membership_id'), 'expenses', ['driver_membership_id'], unique=False)
    op.create_index(op.f('ix_expenses_spent_at'), 'expenses', ['spent_at'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_trip_id'), 'expenses', ['trip_id'], unique=False)
    op.create_index(op.f('ix_expenses_vehicle_id'), 'expenses', ['vehicle_id'], unique=False)
    op.add_column('defects', sa.Column('work_order_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_defects_work_order', 'defects', 'work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_defects_work_order', 'defects', type_='foreignkey')
    op.drop_column('defects', 'work_order_id')
    op.drop_index(op.f('ix_expenses_vehicle_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_trip_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_spent_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_driver_membership_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_business_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_service_reminders_business_id'), table_name='service_reminders')
    op.drop_table('service_reminders')
    op.drop_index(op.f('ix_service_records_vehicle_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_business_id'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_index(op.f('ix_work_order_parts_work_order_id'), table_name='work_order_parts')
    op.drop_index(op.f('ix_work_order_parts_business_id'), table_name='work_order_parts')
    op.drop_table('work_order_parts')
    op.drop_index(op.f('ix_work_orders_vehicle_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_business_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_service_schedules_vehicle_id'), table_name='service_schedules')
    op.drop_index(op.f('ix_service_schedules_business_id'), table_name='service_schedules')
    op.drop_table('service_schedules')
    op.drop_index(op.f('ix_reconciliations_driver_membership_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_day'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_business_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_spend_limits_business_id'), table_name='spend_limits')
    op.drop_table('spend_limits')
    op.drop_index(op.f('ix_route_costs_business_id'), table_name='route_costs')
    op.drop_table('route_costs')
    # ### end Alembic commands ###
