"""tyres parts incidents sos

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-02 18:06:41.477645

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: str | Sequence[str] | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name')
    )
    op.create_index(op.f('ix_parts_business_id'), 'parts', ['business_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('received', 'issued', 'returned', 'counted', name='stockkind', native_enum=False, length=30), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_business_id'), 'stock_movements', ['business_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_part_id'), 'stock_movements', ['part_id'], unique=False)
    op.create_table('tyres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('serial', sa.String(length=60), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('size', sa.String(length=40), nullable=False),
    sa.Column('cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('in_store', 'fitted', 'removed', 'scrapped', name='tyrestatus', native_enum=False, length=30), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('last_vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('fitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fitted_odometer_km', sa.Integer(), nullable=True),
    sa.Column('moved_odometer_km', sa.Integer(), nullable=True),
    sa.Column('km_before', sa.Integer(), nullable=False),
    sa.Column('retreads', sa.Integer(), nullable=False),
    sa.Column('retread_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('last_tread_mm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('last_tread_on', sa.Date(), nullable=True),
    sa.Column('cost_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'serial')
    )
    op.create_index(op.f('ix_tyres_business_id'), 'tyres', ['business_id'], unique=False)
    op.create_index(op.f('ix_tyres_status'), 'tyres', ['status'], unique=False)
    op.create_index(op.f('ix_tyres_vehicle_id'), 'tyres', ['vehicle_id'], unique=False)
    op.create_index('uq_tyres_position', 'tyres', ['vehicle_id', 'position'], unique=True, postgresql_where=sa.text("status = 'fitted'"))
    op.create_table('tyre_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tyre_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('fitted', 'removed', 'rotated', 'tread', 'retreaded', 'scrapped', name='tyreeventkind', native_enum=False, length=30), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('tread_mm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tyre_id'], ['tyres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tyre_events_business_id'), 'tyre_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_tyre_events_tyre_id'), 'tyre_events', ['tyre_id'], unique=False)
    op.create_table('tyre_swap_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=False),
    sa.Column('expected_serial', sa.String(length=60), nullable=True),
    sa.Column('seen_serial', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tyre_swap_alerts_business_id'), 'tyre_swap_alerts', ['business_id'], unique=False)
    op.create_index(op.f('ix_tyre_swap_alerts_status'), 'tyre_swap_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_tyre_swap_alerts_vehicle_id'), 'tyre_swap_alerts', ['vehicle_id'], unique=False)
    op.create_table('sos_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('driver_membership_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('track', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified', sa.Integer(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'client_id')
    )
    op.create_index(op.f('ix_sos_alerts_business_id'), 'sos_alerts', ['business_id'], unique=False)
    op.create_index(op.f('ix_sos_alerts_status'), 'sos_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_sos_alerts_user_id'), 'sos_alerts', ['user_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('breakdown', 'accident', 'police_stop', 'traffic_fine', 'county_cess', 'cargo_theft', name='incidenttype', native_enum=False, length=30), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('driver_membership_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cost_cents', sa.BigInteger(), nullable=True),
    sa.Column('fine_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('fine_payer', sa.Enum('business', 'driver', name='finepayer', native_enum=False, length=30), nullable=True),
    sa.Column('deduct_from_payroll', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('expense_id', sa.Uuid(), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_business_id'), 'incidents', ['business_id'], unique=False)
    op.create_index(op.f('ix_incidents_driver_membership_id'), 'incidents', ['driver_membership_id'], unique=False)
    op.create_index(op.f('ix_incidents_occurred_at'), 'incidents', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_type'), 'incidents', ['type'], unique=False)
    op.create_index(op.f('ix_incidents_vehicle_id'), 'incidents', ['vehicle_id'], unique=False)
    op.create_table('insurance_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('insurer', sa.String(length=120), nullable=False),
    sa.Column('policy_no', sa.String(length=60), nullable=True),
    sa.Column('claim_no', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('filed', 'documents_requested', 'assessed', 'approved', 'paid', 'rejected', name='claimstatus', native_enum=False, length=30), nullable=False),
    sa.Column('amount_claimed_cents', sa.BigInteger(), nullable=True),
    sa.Column('amount_paid_cents', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('document_photo_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_business_id'), 'insurance_claims', ['business_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_incident_id'), 'insurance_claims', ['incident_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_status'), 'insurance_claims', ['status'], unique=False)
    op.add_column('work_order_parts', sa.Column('part_id', sa.Uuid(), nullable=True))
    op.add_column('work_order_parts', sa.Column('fitted', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('work_order_parts', sa.Column('expense_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_work_order_parts_expense_id', 'work_order_parts', 'expenses', ['expense_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_work_order_parts_part_id', 'work_order_parts', 'parts', ['part_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_work_order_parts_part_id', 'work_order_parts', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_work_order_parts_expense_id', 'work_order_parts', type_='foreignkey')
    op.drop_column('work_order_parts', 'expense_id')
    op.drop_column('work_order_parts', 'fitted')
    op.drop_column('work_order_parts', 'part_id')
    op.drop_index(op.f('ix_insurance_claims_status'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_incident_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_business_id'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_index(op.f('ix_incidents_vehicle_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_occurred_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_driver_membership_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_business_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_sos_alerts_user_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_status'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_business_id'), table_name='sos_alerts')
    op.drop_table('sos_alerts')
    op.drop_index(op.f('ix_tyre_swap_alerts_vehicle_id'), table_name='tyre_swap_alerts')
    op.drop_index(op.f('ix_tyre_swap_alerts_status'), table_name='tyre_swap_alerts')
    op.drop_index(op.f('ix_tyre_swap_alerts_business_id'), table_name='tyre_swap_alerts')
    op.drop_table('tyre_swap_alerts')
    op.drop_index(op.f('ix_tyre_events_tyre_id'), table_name='tyre_events')
    op.drop_index(op.f('ix_tyre_events_business_id'), table_name='tyre_events')
    op.drop_table('tyre_events')
    op.drop_index('uq_tyres_position', table_name='tyres', postgresql_where=sa.text("status = 'fitted'"))
    op.drop_index(op.f('ix_tyres_vehicle_id'), table_name='tyres')
    op.drop_index(op.f('ix_tyres_status'), table_name='tyres')
    op.drop_index(op.f('ix_tyres_business_id'), table_name='tyres')
    op.drop_table('tyres')
    op.drop_index(op.f('ix_stock_movements_part_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_business_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_parts_business_id'), table_name='parts')
    op.drop_table('parts')
    # ### end Alembic commands ###
