"""clients routes quotes jobs

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-02 18:38:38.419854

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: str | Sequence[str] | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('kra_pin', sa.String(length=11), nullable=True),
    sa.Column('billing_method', sa.Enum('per_trip', 'per_tonne', 'per_km', 'monthly_contract', name='billingmethod', native_enum=False, length=30), nullable=False),
    sa.Column('rate_cents', sa.BigInteger(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name')
    )
    op.create_index(op.f('ix_clients_business_id'), 'clients', ['business_id'], unique=False)
    op.create_table('saved_routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('pickup', sa.String(length=160), nullable=False),
    sa.Column('dropoff', sa.String(length=160), nullable=False),
    sa.Column('path_notes', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.Column('expected_hours', sa.Float(), nullable=False),
    sa.Column('tolls_cents', sa.BigInteger(), nullable=False),
    sa.Column('crew_cents', sa.BigInteger(), nullable=False),
    sa.Column('other_cents', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'client_id', 'name')
    )
    op.create_index(op.f('ix_saved_routes_business_id'), 'saved_routes', ['business_id'], unique=False)
    op.create_index(op.f('ix_saved_routes_client_id'), 'saved_routes', ['client_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('cargo_description', sa.String(length=255), nullable=True),
    sa.Column('weight_tonnes', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('trips', sa.Integer(), nullable=False),
    sa.Column('return_empty', sa.Boolean(), nullable=False),
    sa.Column('billing_method', sa.Enum('per_trip', 'per_tonne', 'per_km', 'monthly_contract', name='billingmethod', native_enum=False, length=30), nullable=False),
    sa.Column('rate_cents', sa.BigInteger(), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.Column('kmpl_loaded', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('kmpl_empty', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fuel_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('tolls_cents', sa.BigInteger(), nullable=False),
    sa.Column('crew_cents', sa.BigInteger(), nullable=False),
    sa.Column('other_cents', sa.BigInteger(), nullable=False),
    sa.Column('price_cents', sa.BigInteger(), nullable=False),
    sa.Column('total_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('expected_profit_cents', sa.BigInteger(), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'declined', name='quotestatus', native_enum=False, length=30), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deliver_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('sent_via', sa.String(length=20), nullable=True),
    sa.Column('sent_to', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['saved_routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number')
    )
    op.create_index(op.f('ix_quotes_business_id'), 'quotes', ['business_id'], unique=False)
    op.create_index(op.f('ix_quotes_client_id'), 'quotes', ['client_id'], unique=False)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=True),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('repeat_of_id', sa.Uuid(), nullable=True),
    sa.Column('cargo_description', sa.String(length=255), nullable=True),
    sa.Column('weight_tonnes', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('trips_planned', sa.Integer(), nullable=False),
    sa.Column('billing_method', sa.Enum('per_trip', 'per_tonne', 'per_km', 'monthly_contract', name='billingmethod', native_enum=False, length=30), nullable=False),
    sa.Column('rate_cents', sa.BigInteger(), nullable=False),
    sa.Column('price_cents', sa.BigInteger(), nullable=False),
    sa.Column('expected_profit_cents', sa.BigInteger(), nullable=True),
    sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deliver_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'dispatched', 'in_progress', 'completed', 'cancelled', name='jobstatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repeat_of_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['saved_routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number'),
    sa.UniqueConstraint('business_id', 'quote_id')
    )
    op.create_index(op.f('ix_jobs_business_id'), 'jobs', ['business_id'], unique=False)
    op.create_index(op.f('ix_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.add_column('trips', sa.Column('job_id', sa.Uuid(), nullable=True))
    op.add_column('trips', sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_trips_job_id'), 'trips', ['job_id'], unique=False)
    op.create_foreign_key('fk_trips_job_id', 'trips', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_trips_job_id', 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_job_id'), table_name='trips')
    op.drop_column('trips', 'planned_end')
    op.drop_column('trips', 'job_id')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_client_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_business_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_client_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_business_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_saved_routes_client_id'), table_name='saved_routes')
    op.drop_index(op.f('ix_saved_routes_business_id'), table_name='saved_routes')
    op.drop_table('saved_routes')
    op.drop_index(op.f('ix_clients_business_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
