"""proof of delivery weighbridge invoices

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-02 19:04:18.229547

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: str | Sequence[str] | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal_cents', sa.BigInteger(), nullable=False),
    sa.Column('vat_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_cents', sa.BigInteger(), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('paid_cents', sa.BigInteger(), nullable=False),
    sa.Column('void_reason', sa.String(length=255), nullable=True),
    sa.Column('sent_via', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'job_id', 'period_start'),
    sa.UniqueConstraint('business_id', 'number'),
    sa.UniqueConstraint('business_id', 'trip_id')
    )
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('pod_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('sent_to', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_codes_business_id'), 'pod_codes', ['business_id'], unique=False)
    op.create_index(op.f('ix_pod_codes_trip_id'), 'pod_codes', ['trip_id'], unique=False)
    op.create_table('proofs_of_delivery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cargo_photo_id', sa.Uuid(), nullable=True),
    sa.Column('note_photo_id', sa.Uuid(), nullable=True),
    sa.Column('damage_photo_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shortage_qty', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('shortage_unit', sa.String(length=20), nullable=True),
    sa.Column('damage_notes', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cargo_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['note_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'trip_id')
    )
    op.create_index(op.f('ix_proofs_of_delivery_business_id'), 'proofs_of_delivery', ['business_id'], unique=False)
    op.create_index(op.f('ix_proofs_of_delivery_trip_id'), 'proofs_of_delivery', ['trip_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cents', sa.BigInteger(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_business_id'), 'invoice_lines', ['business_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('invoice_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_payments_business_id'), 'invoice_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_invoice_payments_invoice_id'), 'invoice_payments', ['invoice_id'], unique=False)
    op.add_column('clients', sa.Column('vat_pct', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.add_column('saved_routes', sa.Column('dropoff_lat', sa.Float(), nullable=True))
    op.add_column('saved_routes', sa.Column('dropoff_lng', sa.Float(), nullable=True))
    op.add_column('saved_routes', sa.Column('site_radius_m', sa.Integer(), nullable=False, server_default='500'))
    op.add_column('trips', sa.Column('weighbridge_photo_id', sa.Uuid(), nullable=True))
    op.add_column('trips', sa.Column('overload_kg', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_trips_weighbridge_photo_id', 'trips', 'photos', ['weighbridge_photo_id'], ['id'], ondelete='SET NULL')
    op.add_column('vehicles', sa.Column('tare_kg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'tare_kg')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_trips_weighbridge_photo_id', 'trips', type_='foreignkey')
    op.drop_column('trips', 'overload_kg')
    op.drop_column('trips', 'weighbridge_photo_id')
    op.drop_column('saved_routes', 'site_radius_m')
    op.drop_column('saved_routes', 'dropoff_lng')
    op.drop_column('saved_routes', 'dropoff_lat')
    op.drop_column('clients', 'vat_pct')
    op.drop_index(op.f('ix_invoice_payments_invoice_id'), table_name='invoice_payments')
    op.drop_index(op.f('ix_invoice_payments_business_id'), table_name='invoice_payments')
    op.drop_table('invoice_payments')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_business_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_proofs_of_delivery_trip_id'), table_name='proofs_of_delivery')
    op.drop_index(op.f('ix_proofs_of_delivery_business_id'), table_name='proofs_of_delivery')
    op.drop_table('proofs_of_delivery')
    op.drop_index(op.f('ix_pod_codes_trip_id'), table_name='pod_codes')
    op.drop_index(op.f('ix_pod_codes_business_id'), table_name='pod_codes')
    op.drop_table('pod_codes')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
