"""payments debtors reminders etims

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-02 20:01:23.850634

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: str | Sequence[str] | None = '0012'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_statement_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('new_rows', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_statement_imports_business_id'), 'mpesa_statement_imports', ['business_id'], unique=False)
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trans_id', sa.String(length=12), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('allocated_cents', sa.BigInteger(), nullable=False),
    sa.Column('bill_ref', sa.String(length=60), nullable=True),
    sa.Column('payer_name', sa.String(length=160), nullable=True),
    sa.Column('payer_phone', sa.String(length=80), nullable=True),
    sa.Column('shortcode', sa.String(length=10), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=True),
    sa.Column('dismissed_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'trans_id')
    )
    op.create_index(op.f('ix_mpesa_transactions_business_id'), 'mpesa_transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_status'), 'mpesa_transactions', ['status'], unique=False)
    op.create_table('payment_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shortcode', sa.String(length=10), nullable=True),
    sa.Column('shortcode_type', sa.String(length=8), nullable=False),
    sa.Column('urls_registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminders_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('reminder_offsets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reminder_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('etims_enabled', sa.Boolean(), nullable=False),
    sa.Column('etims_branch_id', sa.String(length=2), nullable=False),
    sa.Column('etims_device_serial', sa.String(length=100), nullable=True),
    sa.Column('etims_zero_vat_code', sa.String(length=1), nullable=False),
    sa.Column('etims_item_code', sa.String(length=20), nullable=False),
    sa.Column('etims_item_class_code', sa.String(length=10), nullable=False),
    sa.Column('etims_pkg_unit', sa.String(length=5), nullable=False),
    sa.Column('etims_qty_unit', sa.String(length=5), nullable=False),
    sa.Column('etims_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index(op.f('ix_payment_settings_business_id'), 'payment_settings', ['business_id'], unique=False)
    op.create_table('mpesa_statement_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_id', sa.Uuid(), nullable=True),
    sa.Column('receipt', sa.String(length=12), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('paid_in_cents', sa.BigInteger(), nullable=False),
    sa.Column('withdrawn_cents', sa.BigInteger(), nullable=False),
    sa.Column('match_kind', sa.String(length=16), nullable=True),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=14), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_id'], ['mpesa_statement_imports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'receipt')
    )
    op.create_index(op.f('ix_mpesa_statement_lines_business_id'), 'mpesa_statement_lines', ['business_id'], unique=False)
    op.create_index(op.f('ix_mpesa_statement_lines_completed_at'), 'mpesa_statement_lines', ['completed_at'], unique=False)
    op.create_index(op.f('ix_mpesa_statement_lines_import_id'), 'mpesa_statement_lines', ['import_id'], unique=False)
    op.create_index(op.f('ix_mpesa_statement_lines_state'), 'mpesa_statement_lines', ['state'], unique=False)
    op.create_table('etims_submissions',
    sa.Column('invoice_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('receipt_no', sa.String(length=40), nullable=True),
    sa.Column('sdc_id', sa.String(length=40), nullable=True),
    sa.Column('sdc_time', sa.String(length=20), nullable=True),
    sa.Column('receipt_signature', sa.String(length=200), nullable=True),
    sa.Column('internal_data', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'invoice_id', 'kind'),
    sa.UniqueConstraint('business_id', 'invoice_no')
    )
    op.create_index(op.f('ix_etims_submissions_business_id'), 'etims_submissions', ['business_id'], unique=False)
    op.create_index(op.f('ix_etims_submissions_invoice_id'), 'etims_submissions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_etims_submissions_next_attempt_at'), 'etims_submissions', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_etims_submissions_status'), 'etims_submissions', ['status'], unique=False)
    op.create_table('payment_reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('sent_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'invoice_id', 'offset_days', 'channel')
    )
    op.create_index(op.f('ix_payment_reminders_business_id'), 'payment_reminders', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_reminders_invoice_id'), 'payment_reminders', ['invoice_id'], unique=False)
    op.add_column('clients', sa.Column('reminders_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('invoice_payments', sa.Column('mpesa_transaction_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_invoice_payments_mpesa_transaction_id'), 'invoice_payments', ['mpesa_transaction_id'], unique=False)
    op.create_foreign_key('fk_invoice_payments_mpesa_transaction_id', 'invoice_payments', 'mpesa_transactions', ['mpesa_transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoice_payments_mpesa_transaction_id', 'invoice_payments', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_payments_mpesa_transaction_id'), table_name='invoice_payments')
    op.drop_column('invoice_payments', 'mpesa_transaction_id')
    op.drop_column('clients', 'reminders_enabled')
    op.drop_index(op.f('ix_payment_reminders_invoice_id'), table_name='payment_reminders')
    op.drop_index(op.f('ix_payment_reminders_business_id'), table_name='payment_reminders')
    op.drop_table('payment_reminders')
    op.drop_index(op.f('ix_etims_submissions_status'), table_name='etims_submissions')
    op.drop_index(op.f('ix_etims_submissions_next_attempt_at'), table_name='etims_submissions')
    op.drop_index(op.f('ix_etims_submissions_invoice_id'), table_name='etims_submissions')
    op.drop_index(op.f('ix_etims_submissions_business_id'), table_name='etims_submissions')
    op.drop_table('etims_submissions')
    op.drop_index(op.f('ix_mpesa_statement_lines_state'), table_name='mpesa_statement_lines')
    op.drop_index(op.f('ix_mpesa_statement_lines_import_id'), table_name='mpesa_statement_lines')
    op.drop_index(op.f('ix_mpesa_statement_lines_completed_at'), table_name='mpesa_statement_lines')
    op.drop_index(op.f('ix_mpesa_statement_lines_business_id'), table_name='mpesa_statement_lines')
    op.drop_table('mpesa_statement_lines')
    op.drop_index(op.f('ix_payment_settings_business_id'), table_name='payment_settings')
    op.drop_table('payment_settings')
    op.drop_index(op.f('ix_mpesa_transactions_status'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_business_id'), table_name='mpesa_transactions')
    op.drop_table('mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_statement_imports_business_id'), table_name='mpesa_statement_imports')
    op.drop_table('mpesa_statement_imports')
    # ### end Alembic commands ###
