"""leasing finance ownership payroll suppliers

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-02 21:56:00.557511

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: str | Sequence[str] | None = '0013'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'month')
    )
    op.create_index(op.f('ix_payroll_runs_business_id'), 'payroll_runs', ['business_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name')
    )
    op.create_index(op.f('ix_suppliers_business_id'), 'suppliers', ['business_id'], unique=False)
    op.create_table('parts_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('expected_on', sa.Date(), nullable=True),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_reference', sa.String(length=60), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number')
    )
    op.create_index(op.f('ix_parts_orders_business_id'), 'parts_orders', ['business_id'], unique=False)
    op.create_index(op.f('ix_parts_orders_status'), 'parts_orders', ['status'], unique=False)
    op.create_index(op.f('ix_parts_orders_supplier_id'), 'parts_orders', ['supplier_id'], unique=False)
    op.create_table('finance_agreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('principal_cents', sa.BigInteger(), nullable=False),
    sa.Column('annual_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('first_due', sa.Date(), nullable=False),
    sa.Column('instalment_cents', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_agreements_business_id'), 'finance_agreements', ['business_id'], unique=False)
    op.create_index(op.f('ix_finance_agreements_vehicle_id'), 'finance_agreements', ['vehicle_id'], unique=False)
    op.create_table('lease_agreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notice_days', sa.Integer(), nullable=False),
    sa.Column('deposit_cents', sa.BigInteger(), nullable=False),
    sa.Column('fixed_cents', sa.BigInteger(), nullable=False),
    sa.Column('fixed_period', sa.String(length=5), nullable=True),
    sa.Column('per_trip_cents', sa.BigInteger(), nullable=False),
    sa.Column('per_km_cents', sa.BigInteger(), nullable=False),
    sa.Column('revenue_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_guarantee_cents', sa.BigInteger(), nullable=False),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payment_due_days', sa.Integer(), nullable=False),
    sa.Column('share_trips', sa.Boolean(), nullable=False),
    sa.Column('share_location', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lease_agreements_business_id'), 'lease_agreements', ['business_id'], unique=False)
    op.create_index(op.f('ix_lease_agreements_party_id'), 'lease_agreements', ['party_id'], unique=False)
    op.create_index(op.f('ix_lease_agreements_vehicle_id'), 'lease_agreements', ['vehicle_id'], unique=False)
    op.create_index('uq_lease_active_vehicle', 'lease_agreements', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('ownership_costs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('salvage_cents', sa.BigInteger(), nullable=False),
    sa.Column('life_months', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_costs_business_id'), 'ownership_costs', ['business_id'], unique=False)
    op.create_index(op.f('ix_ownership_costs_vehicle_id'), 'ownership_costs', ['vehicle_id'], unique=False)
    op.create_table('parts_order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['parts_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_order_lines_business_id'), 'parts_order_lines', ['business_id'], unique=False)
    op.create_index(op.f('ix_parts_order_lines_order_id'), 'parts_order_lines', ['order_id'], unique=False)
    op.create_table('payroll_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('gross_cents', sa.BigInteger(), nullable=False),
    sa.Column('advances_cents', sa.BigInteger(), nullable=False),
    sa.Column('fines_cents', sa.BigInteger(), nullable=False),
    sa.Column('net_cents', sa.BigInteger(), nullable=False),
    sa.Column('deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'membership_id')
    )
    op.create_index(op.f('ix_payroll_lines_business_id'), 'payroll_lines', ['business_id'], unique=False)
    op.create_index(op.f('ix_payroll_lines_membership_id'), 'payroll_lines', ['membership_id'], unique=False)
    op.create_index(op.f('ix_payroll_lines_run_id'), 'payroll_lines', ['run_id'], unique=False)
    op.create_table('salary_advances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('remaining_cents', sa.BigInteger(), nullable=False),
    sa.Column('given_on', sa.Date(), nullable=False),
    sa.Column('mpesa_code', sa.String(length=12), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_advances_business_id'), 'salary_advances', ['business_id'], unique=False)
    op.create_index(op.f('ix_salary_advances_membership_id'), 'salary_advances', ['membership_id'], unique=False)
    op.create_table('finance_instalments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('interest_cents', sa.BigInteger(), nullable=False),
    sa.Column('principal_cents', sa.BigInteger(), nullable=False),
    sa.Column('paid_cents', sa.BigInteger(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('mpesa_code', sa.String(length=12), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['finance_agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id', 'number')
    )
    op.create_index(op.f('ix_finance_instalments_agreement_id'), 'finance_instalments', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_finance_instalments_business_id'), 'finance_instalments', ['business_id'], unique=False)
    op.create_index(op.f('ix_finance_instalments_due_date'), 'finance_instalments', ['due_date'], unique=False)
    op.create_table('lease_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_kind', sa.String(length=10), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('mpesa_code', sa.String(length=12), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['lease_agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'mpesa_code'),
    sa.UniqueConstraint('business_id', 'source_kind', 'source_id')
    )
    op.create_index(op.f('ix_lease_entries_agreement_id'), 'lease_entries', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_lease_entries_business_id'), 'lease_entries', ['business_id'], unique=False)
    op.create_index('uq_lease_charge_period', 'lease_entries', ['agreement_id', 'period_start'], unique=True, postgresql_where=sa.text("kind = 'charge'"))
    op.create_table('lease_notices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('sent_to', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['lease_agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'agreement_id', 'period_start', 'kind')
    )
    op.create_index(op.f('ix_lease_notices_agreement_id'), 'lease_notices', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_lease_notices_business_id'), 'lease_notices', ['business_id'], unique=False)
    op.add_column('incidents', sa.Column('payroll_deducted_cents', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('memberships', sa.Column('party_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_memberships_party_id', 'memberships', 'parties', ['party_id'], ['id'], ondelete='SET NULL')
    op.add_column('parties', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'email')
    op.drop_constraint('fk_memberships_party_id', 'memberships', type_='foreignkey')
    op.drop_column('memberships', 'party_id')
    op.drop_column('incidents', 'payroll_deducted_cents')
    op.drop_index(op.f('ix_lease_notices_business_id'), table_name='lease_notices')
    op.drop_index(op.f('ix_lease_notices_agreement_id'), table_name='lease_notices')
    op.drop_table('lease_notices')
    op.drop_index('uq_lease_charge_period', table_name='lease_entries', postgresql_where=sa.text("kind = 'charge'"))
    op.drop_index(op.f('ix_lease_entries_business_id'), table_name='lease_entries')
    op.drop_index(op.f('ix_lease_entries_agreement_id'), table_name='lease_entries')
    op.drop_table('lease_entries')
    op.drop_index(op.f('ix_finance_instalments_due_date'), table_name='finance_instalments')
    op.drop_index(op.f('ix_finance_instalments_business_id'), table_name='finance_instalments')
    op.drop_index(op.f('ix_finance_instalments_agreement_id'), table_name='finance_instalments')
    op.drop_table('finance_instalments')
    op.drop_index(op.f('ix_salary_advances_membership_id'), table_name='salary_advances')
    op.drop_index(op.f('ix_salary_advances_business_id'), table_name='salary_advances')
    op.drop_table('salary_advances')
    op.drop_index(op.f('ix_payroll_lines_run_id'), table_name='payroll_lines')
    op.drop_index(op.f('ix_payroll_lines_membership_id'), table_name='payroll_lines')
    op.drop_index(op.f('ix_payroll_lines_business_id'), table_name='payroll_lines')
    op.drop_table('payroll_lines')
    op.drop_index(op.f('ix_parts_order_lines_order_id'), table_name='parts_order_lines')
    op.drop_index(op.f('ix_parts_order_lines_business_id'), table_name='parts_order_lines')
    op.drop_table('parts_order_lines')
    op.drop_index(op.f('ix_ownership_costs_vehicle_id'), table_name='ownership_costs')
    op.drop_index(op.f('ix_ownership_costs_business_id'), table_name='ownership_costs')
    op.drop_table('ownership_costs')
    op.drop_index('uq_lease_active_vehicle', table_name='lease_agreements', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_lease_agreements_vehicle_id'), table_name='lease_agreements')
    op.drop_index(op.f('ix_lease_agreements_party_id'), table_name='lease_agreements')
    op.drop_index(op.f('ix_lease_agreements_business_id'), table_name='lease_agreements')
    op.drop_table('lease_agreements')
    op.drop_index(op.f('ix_finance_agreements_vehicle_id'), table_name='finance_agreements')
    op.drop_index(op.f('ix_finance_agreements_business_id'), table_name='finance_agreements')
    op.drop_table('finance_agreements')
    op.drop_index(op.f('ix_parts_orders_supplier_id'), table_name='parts_orders')
    op.drop_index(op.f('ix_parts_orders_status'), table_name='parts_orders')
    op.drop_index(op.f('ix_parts_orders_business_id'), table_name='parts_orders')
    op.drop_table('parts_orders')
    op.drop_index(op.f('ix_suppliers_business_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_payroll_runs_business_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    # ### end Alembic commands ###
