"""phone gps tracking links

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-02 23:24:18.212360

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: str | Sequence[str] | None = '0014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    sa.UniqueConstraint('business_id', 'vehicle_id', 'recorded_at')
    )
    op.create_index(op.f('ix_location_points_business_id'), 'location_points', ['business_id'], unique=False)
    # A time-series table: split into week-long chunks by the time the phone took the fix.
    # Only where TimescaleDB is installed; on plain PostgreSQL it stays an ordinary table.
    op.execute(
        "DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN "
        "PERFORM create_hypertable('location_points', 'recorded_at', chunk_time_interval => INTERVAL '7 days'); END IF; END $$"
    )
    op.create_index('ix_location_points_trip_time', 'location_points', ['trip_id', 'recorded_at'], unique=False)
    op.create_index('ix_location_points_vehicle_time', 'location_points', ['vehicle_id', 'recorded_at'], unique=False)
    op.create_table('tracking_gaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_gaps_business_id'), 'tracking_gaps', ['business_id'], unique=False)
    op.create_index(op.f('ix_tracking_gaps_resolved_at'), 'tracking_gaps', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_tracking_gaps_trip_id'), 'tracking_gaps', ['trip_id'], unique=False)
    op.create_index(op.f('ix_tracking_gaps_vehicle_id'), 'tracking_gaps', ['vehicle_id'], unique=False)
    op.create_table('tracking_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_to', sa.String(length=20), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_tracking_links_business_id'), 'tracking_links', ['business_id'], unique=False)
    op.create_index(op.f('ix_tracking_links_trip_id'), 'tracking_links', ['trip_id'], unique=False)
    op.add_column('trips', sa.Column('gps_distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('gps_points', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('distance_check', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'distance_check')
    op.drop_column('trips', 'gps_points')
    op.drop_column('trips', 'gps_distance_km')
    op.drop_index(op.f('ix_tracking_links_trip_id'), table_name='tracking_links')
    op.drop_index(op.f('ix_tracking_links_business_id'), table_name='tracking_links')
    op.drop_table('tracking_links')
    op.drop_index(op.f('ix_tracking_gaps_vehicle_id'), table_name='tracking_gaps')
    op.drop_index(op.f('ix_tracking_gaps_trip_id'), table_name='tracking_gaps')
    op.drop_index(op.f('ix_tracking_gaps_resolved_at'), table_name='tracking_gaps')
    op.drop_index(op.f('ix_tracking_gaps_business_id'), table_name='tracking_gaps')
    op.drop_table('tracking_gaps')
    op.drop_index('ix_location_points_vehicle_time', table_name='location_points')
    op.drop_index('ix_location_points_trip_time', table_name='location_points')
    op.drop_index(op.f('ix_location_points_business_id'), table_name='location_points')
    op.drop_table('location_points')
    # ### end Alembic commands ###
