"""trackers geofences alerts behaviour immobiliser

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-03 07:06:20.562866

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0016'
down_revision: str | Sequence[str] | None = '0015'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=14), nullable=False),
    sa.Column('shape', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vehicle_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name')
    )
    op.create_index(op.f('ix_geofences_business_id'), 'geofences', ['business_id'], unique=False)
    op.create_table('behaviour_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_behaviour_state_business_id'), 'behaviour_state', ['business_id'], unique=False)
    op.create_table('geofence_presence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('geofence_id', sa.Uuid(), nullable=False),
    sa.Column('inside', sa.Boolean(), nullable=True),
    sa.Column('pending', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'geofence_id')
    )
    op.create_index(op.f('ix_geofence_presence_business_id'), 'geofence_presence', ['business_id'], unique=False)
    op.create_index(op.f('ix_geofence_presence_geofence_id'), 'geofence_presence', ['geofence_id'], unique=False)
    op.create_index(op.f('ix_geofence_presence_vehicle_id'), 'geofence_presence', ['vehicle_id'], unique=False)
    op.create_table('tracker_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('imei', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('brand', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('sim_phone', sa.String(length=20), nullable=True),
    sa.Column('supports_immobiliser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_position_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('power_v', sa.Float(), nullable=True),
    sa.Column('power_ok', sa.Boolean(), nullable=True),
    sa.Column('ignition', sa.Boolean(), nullable=True),
    sa.Column('gps_ok', sa.Boolean(), nullable=True),
    sa.Column('online_state', sa.String(length=8), nullable=False),
    sa.Column('immobilised', sa.Boolean(), nullable=False),
    sa.Column('traccar_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imei')
    )
    op.create_index(op.f('ix_tracker_devices_business_id'), 'tracker_devices', ['business_id'], unique=False)
    op.create_index(op.f('ix_tracker_devices_vehicle_id'), 'tracker_devices', ['vehicle_id'], unique=False)
    op.create_table('immobiliser_commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=22), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('position_age_s', sa.Integer(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_note', sa.String(length=255), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['tracker_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immobiliser_commands_business_id'), 'immobiliser_commands', ['business_id'], unique=False)
    op.create_index(op.f('ix_immobiliser_commands_status'), 'immobiliser_commands', ['status'], unique=False)
    op.create_index(op.f('ix_immobiliser_commands_vehicle_id'), 'immobiliser_commands', ['vehicle_id'], unique=False)
    op.create_table('behaviour_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('driver_membership_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'vehicle_id', 'kind', 'at')
    )
    op.create_index(op.f('ix_behaviour_events_business_id'), 'behaviour_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_behaviour_events_driver_membership_id'), 'behaviour_events', ['driver_membership_id'], unique=False)
    op.create_index(op.f('ix_behaviour_events_kind'), 'behaviour_events', ['kind'], unique=False)
    op.create_index(op.f('ix_behaviour_events_trip_id'), 'behaviour_events', ['trip_id'], unique=False)
    op.create_index('ix_behaviour_vehicle_time', 'behaviour_events', ['vehicle_id', 'at'], unique=False)
    op.create_table('geofence_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('geofence_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=5), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofence_events_at'), 'geofence_events', ['at'], unique=False)
    op.create_index(op.f('ix_geofence_events_business_id'), 'geofence_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_geofence_events_geofence_id'), 'geofence_events', ['geofence_id'], unique=False)
    op.create_index(op.f('ix_geofence_events_vehicle_id'), 'geofence_events', ['vehicle_id'], unique=False)
    op.create_table('tracker_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=5), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('handled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['tracker_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_alerts_at'), 'tracker_alerts', ['at'], unique=False)
    op.create_index(op.f('ix_tracker_alerts_business_id'), 'tracker_alerts', ['business_id'], unique=False)
    op.create_index(op.f('ix_tracker_alerts_kind'), 'tracker_alerts', ['kind'], unique=False)
    op.create_index(op.f('ix_tracker_alerts_status'), 'tracker_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_tracker_alerts_vehicle_id'), 'tracker_alerts', ['vehicle_id'], unique=False)
    op.add_column('location_points', sa.Column('ignition', sa.Boolean(), nullable=True))
    op.add_column('trips', sa.Column('tracker_distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('tracker_points', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('distance_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'distance_detail')
    op.drop_column('trips', 'tracker_points')
    op.drop_column('trips', 'tracker_distance_km')
    op.drop_column('location_points', 'ignition')
    op.drop_index(op.f('ix_tracker_alerts_vehicle_id'), table_name='tracker_alerts')
    op.drop_index(op.f('ix_tracker_alerts_status'), table_name='tracker_alerts')
    op.drop_index(op.f('ix_tracker_alerts_kind'), table_name='tracker_alerts')
    op.drop_index(op.f('ix_tracker_alerts_business_id'), table_name='tracker_alerts')
    op.drop_index(op.f('ix_tracker_alerts_at'), table_name='tracker_alerts')
    op.drop_table('tracker_alerts')
    op.drop_index(op.f('ix_geofence_events_vehicle_id'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_geofence_id'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_business_id'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_at'), table_name='geofence_events')
    op.drop_table('geofence_events')
    op.drop_index('ix_behaviour_vehicle_time', table_name='behaviour_events')
    op.drop_index(op.f('ix_behaviour_events_trip_id'), table_name='behaviour_events')
    op.drop_index(op.f('ix_behaviour_events_kind'), table_name='behaviour_events')
    op.drop_index(op.f('ix_behaviour_events_driver_membership_id'), table_name='behaviour_events')
    op.drop_index(op.f('ix_behaviour_events_business_id'), table_name='behaviour_events')
    op.drop_table('behaviour_events')
    op.drop_index(op.f('ix_immobiliser_commands_vehicle_id'), table_name='immobiliser_commands')
    op.drop_index(op.f('ix_immobiliser_commands_status'), table_name='immobiliser_commands')
    op.drop_index(op.f('ix_immobiliser_commands_business_id'), table_name='immobiliser_commands')
    op.drop_table('immobiliser_commands')
    op.drop_index(op.f('ix_tracker_devices_vehicle_id'), table_name='tracker_devices')
    op.drop_index(op.f('ix_tracker_devices_business_id'), table_name='tracker_devices')
    op.drop_table('tracker_devices')
    op.drop_index(op.f('ix_geofence_presence_vehicle_id'), table_name='geofence_presence')
    op.drop_index(op.f('ix_geofence_presence_geofence_id'), table_name='geofence_presence')
    op.drop_index(op.f('ix_geofence_presence_business_id'), table_name='geofence_presence')
    op.drop_table('geofence_presence')
    op.drop_index(op.f('ix_behaviour_state_business_id'), table_name='behaviour_state')
    op.drop_table('behaviour_state')
    op.drop_index(op.f('ix_geofences_business_id'), table_name='geofences')
    op.drop_table('geofences')
    # ### end Alembic commands ###
