"""fraud alerts, alert settings, fuel prices, feedback, onboarding

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-03 09:49:28.997165

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: str | Sequence[str] | None = '0016'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index(op.f('ix_alert_settings_business_id'), 'alert_settings', ['business_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('page', sa.String(length=200), nullable=True),
    sa.Column('app', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_business_id'), 'feedback', ['business_id'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_table('fuel_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('diesel_cents', sa.Integer(), nullable=False),
    sa.Column('petrol_cents', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'month', 'region')
    )
    op.create_index(op.f('ix_fuel_prices_business_id'), 'fuel_prices', ['business_id'], unique=False)
    op.create_index(op.f('ix_fuel_prices_month'), 'fuel_prices', ['month'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=5), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('driver_membership_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.String(length=30), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trust_level', sa.String(length=6), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('handled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'dedupe_key')
    )
    op.create_index(op.f('ix_fraud_alerts_business_id'), 'fraud_alerts', ['business_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_driver_membership_id'), 'fraud_alerts', ['driver_membership_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_kind'), 'fraud_alerts', ['kind'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_status'), 'fraud_alerts', ['status'], unique=False)
    op.create_index('ix_fraud_alerts_status_created', 'fraud_alerts', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_trip_id'), 'fraud_alerts', ['trip_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_vehicle_id'), 'fraud_alerts', ['vehicle_id'], unique=False)
    op.add_column('businesses', sa.Column('onboarding_dismissed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('fuel_region', sa.String(length=40), server_default=sa.text("'Nairobi'"), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_alerts_vehicle_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_trip_id'), table_name='fraud_alerts')
    op.drop_index('ix_fraud_alerts_status_created', table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_status'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_kind'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_driver_membership_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_business_id'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_fuel_prices_month'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_business_id'), table_name='fuel_prices')
    op.drop_table('fuel_prices')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_business_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_alert_settings_business_id'), table_name='alert_settings')
    op.drop_table('alert_settings')
    op.drop_column('businesses', 'fuel_region')
    op.drop_column('businesses', 'onboarding_dismissed_at')
    # ### end Alembic commands ###
