"""fuel sensors, vehicle models, document readings

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-03 14:51:21.104447

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: str | Sequence[str] | None = '0017'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('read_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('confirmed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corrections', sa.Integer(), nullable=False),
    sa.Column('read_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['read_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_readings_business_id'), 'document_readings', ['business_id'], unique=False)
    op.create_index(op.f('ix_document_readings_photo_id'), 'document_readings', ['photo_id'], unique=False)
    op.create_index(op.f('ix_document_readings_status'), 'document_readings', ['status'], unique=False)
    op.create_table('vehicle_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('trips', sa.Integer(), nullable=False),
    sa.Column('r2', sa.Float(), nullable=False),
    sa.Column('sigma_litres', sa.Float(), nullable=False),
    sa.Column('reliable', sa.Boolean(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'kind')
    )
    op.create_index(op.f('ix_vehicle_models_business_id'), 'vehicle_models', ['business_id'], unique=False)
    op.create_index(op.f('ix_vehicle_models_vehicle_id'), 'vehicle_models', ['vehicle_id'], unique=False)
    op.add_column('location_points', sa.Column('fuel_litres', sa.Float(), nullable=True))
    op.add_column('quotes', sa.Column('fuel_source', sa.String(length=40), nullable=True))
    op.add_column('quotes', sa.Column('fuel_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quotes', sa.Column('lease_charge_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('quotes', sa.Column('net_profit_cents', sa.BigInteger(), nullable=True))
    op.add_column('quotes', sa.Column('lease_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tracker_devices', sa.Column('has_fuel_sensor', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tracker_devices', sa.Column('fuel_unit', sa.String(length=8), server_default=sa.text("'litres'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_devices', 'fuel_unit')
    op.drop_column('tracker_devices', 'has_fuel_sensor')
    op.drop_column('quotes', 'lease_detail')
    op.drop_column('quotes', 'net_profit_cents')
    op.drop_column('quotes', 'lease_charge_cents')
    op.drop_column('quotes', 'fuel_detail')
    op.drop_column('quotes', 'fuel_source')
    op.drop_column('location_points', 'fuel_litres')
    op.drop_index(op.f('ix_vehicle_models_vehicle_id'), table_name='vehicle_models')
    op.drop_index(op.f('ix_vehicle_models_business_id'), table_name='vehicle_models')
    op.drop_table('vehicle_models')
    op.drop_index(op.f('ix_document_readings_status'), table_name='document_readings')
    op.drop_index(op.f('ix_document_readings_photo_id'), table_name='document_readings')
    op.drop_index(op.f('ix_document_readings_business_id'), table_name='document_readings')
    op.drop_table('document_readings')
    # ### end Alembic commands ###
