"""subscriptions, messaging, exports, questions

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-03 20:01:40.953579

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0019'
down_revision: str | Sequence[str] | None = '0018'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=4000), nullable=True),
    sa.Column('lookups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ask_questions_business_id'), 'ask_questions', ['business_id'], unique=False)
    op.create_index(op.f('ix_ask_questions_created_at'), 'ask_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ask_questions_user_id'), 'ask_questions', ['user_id'], unique=False)
    op.create_table('data_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('include_photos', sa.Boolean(), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('tables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_exports_business_id'), 'data_exports', ['business_id'], unique=False)
    op.create_index(op.f('ix_data_exports_status'), 'data_exports', ['status'], unique=False)
    op.create_table('sms_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('sent_total', sa.Integer(), nullable=False),
    sa.Column('sent_month', sa.Date(), nullable=True),
    sa.Column('sent_this_month', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index(op.f('ix_sms_accounts_business_id'), 'sms_accounts', ['business_id'], unique=False)
    op.create_table('subscription_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_period', sa.String(length=8), nullable=True),
    sa.Column('sms_messages', sa.Integer(), nullable=True),
    sa.Column('quote', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=10), nullable=True),
    sa.Column('mpesa_code', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'number')
    )
    op.create_index(op.f('ix_subscription_invoices_business_id'), 'subscription_invoices', ['business_id'], unique=False)
    op.create_index(op.f('ix_subscription_invoices_status'), 'subscription_invoices', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('payroll_enabled', sa.Boolean(), nullable=False),
    sa.Column('custom_monthly_cents', sa.BigInteger(), nullable=True),
    sa.Column('last_notice', sa.String(length=40), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index(op.f('ix_subscriptions_business_id'), 'subscriptions', ['business_id'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('checkout_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('result_note', sa.String(length=255), nullable=True),
    sa.Column('mpesa_code', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['subscription_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_id')
    )
    op.create_index(op.f('ix_subscription_payments_business_id'), 'subscription_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_invoice_id'), 'subscription_payments', ['invoice_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('also_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_business_id'), 'messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_job_id'), 'messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_messages_trip_id'), 'messages', ['trip_id'], unique=False)
    op.create_table('message_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'membership_id')
    )
    op.create_index(op.f('ix_message_recipients_business_id'), 'message_recipients', ['business_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_membership_id'), 'message_recipients', ['membership_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_message_id'), 'message_recipients', ['message_id'], unique=False)
    op.add_column('businesses', sa.Column('complimentary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('businesses', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('suspended_reason', sa.String(length=255), nullable=True))
    op.execute("UPDATE businesses SET complimentary = true")  # everything that exists before billing starts is the pilot or development data
    op.add_column('clients', sa.Column('is_sample', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('jobs', sa.Column('is_sample', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('report_schedules', sa.Column('report', sa.String(length=30), server_default=sa.text("'summary'"), nullable=False))
    op.add_column('report_schedules', sa.Column('file_format', sa.String(length=5), server_default=sa.text("'pdf'"), nullable=False))
    op.add_column('saved_routes', sa.Column('is_sample', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('vehicles', sa.Column('plan', sa.String(length=10), server_default=sa.text("'standard'"), nullable=False))
    op.add_column('vehicles', sa.Column('is_sample', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_sample')
    op.drop_column('vehicles', 'plan')
    op.drop_column('saved_routes', 'is_sample')
    op.drop_column('report_schedules', 'file_format')
    op.drop_column('report_schedules', 'report')
    op.drop_column('jobs', 'is_sample')
    op.drop_column('clients', 'is_sample')
    op.drop_column('businesses', 'suspended_reason')
    op.drop_column('businesses', 'suspended_at')
    op.drop_column('businesses', 'complimentary')
    op.drop_index(op.f('ix_message_recipients_message_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_membership_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_business_id'), table_name='message_recipients')
    op.drop_table('message_recipients')
    op.drop_index(op.f('ix_messages_trip_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_job_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_business_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_subscription_payments_invoice_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_business_id'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_subscriptions_business_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_subscription_invoices_status'), table_name='subscription_invoices')
    op.drop_index(op.f('ix_subscription_invoices_business_id'), table_name='subscription_invoices')
    op.drop_table('subscription_invoices')
    op.drop_index(op.f('ix_sms_accounts_business_id'), table_name='sms_accounts')
    op.drop_table('sms_accounts')
    op.drop_index(op.f('ix_data_exports_status'), table_name='data_exports')
    op.drop_index(op.f('ix_data_exports_business_id'), table_name='data_exports')
    op.drop_table('data_exports')
    op.drop_index(op.f('ix_ask_questions_user_id'), table_name='ask_questions')
    op.drop_index(op.f('ix_ask_questions_created_at'), table_name='ask_questions')
    op.drop_index(op.f('ix_ask_questions_business_id'), table_name='ask_questions')
    op.drop_table('ask_questions')
    # ### end Alembic commands ###
