"""retention, privacy requests, breach register

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-03 23:30:04.730453

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0020'
down_revision: str | Sequence[str] | None = '0019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breach_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('businesses_affected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('people_affected', sa.Integer(), nullable=True),
    sa.Column('data_involved', sa.String(length=500), nullable=True),
    sa.Column('risk_to_people', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odpc_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('businesses_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('people_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_incidents_status'), 'breach_incidents', ['status'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('details', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('resolution', sa.String(length=2000), nullable=True),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_business_id'), 'data_subject_requests', ['business_id'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_created_at'), 'data_subject_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_membership_id'), 'data_subject_requests', ['membership_id'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_status'), 'data_subject_requests', ['status'], unique=False)
    op.add_column('businesses', sa.Column('wound_down_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memberships', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memberships', sa.Column('anonymised_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('photos', sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))

    # People who had already left have no date for it yet: start their retention clock now, never earlier.
    op.execute("UPDATE memberships SET revoked_at = now() WHERE status = 'revoked' AND revoked_at IS NULL")

    # The audit log stays append-only, with one narrow exception for the retention policy (masterplan 11.3): a row may be deleted
    # when the job that does it says so AND the row is more than five years old, or the whole business is being erased at the end
    # of its legal retention. The age check is here, in the database, so a mistake in the job cannot delete recent history.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_logs_immutable() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE'
               AND current_setting('app.audit_purge', true) = 'on'
               AND (OLD.created_at < now() - interval '5 years'
                    OR current_setting('app.business_erasure', true) = OLD.business_id::text) THEN
                RETURN OLD;
            END IF;
            RAISE EXCEPTION 'audit_logs is append-only';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'purged_at')
    op.drop_column('memberships', 'anonymised_at')
    op.drop_column('memberships', 'revoked_at')
    op.drop_column('businesses', 'wound_down_at')
    op.drop_index(op.f('ix_data_subject_requests_status'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_membership_id'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_created_at'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_business_id'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_breach_incidents_status'), table_name='breach_incidents')
    op.drop_table('breach_incidents')
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_logs_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_logs is append-only';
        END;
        $$ LANGUAGE plpgsql
        """
    )

