"""indexes for large fleets

Revision ID: 0021
Revises: 0020
Create Date: 2026-10-04 00:28:46.718901

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: str | Sequence[str] | None = '0020'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_business_created', 'audit_logs', ['business_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_behaviour_driver_time', 'behaviour_events', ['driver_membership_id', 'at'], unique=False)
    op.create_index('ix_expenses_business_spent', 'expenses', ['business_id', 'spent_at'], unique=False)
    op.create_index('ix_fuel_entries_business_captured', 'fuel_entries', ['business_id', 'captured_at'], unique=False)
    op.create_index('ix_trips_business_ended', 'trips', ['business_id', 'ended_at'], unique=False)
    op.create_index('ix_trips_business_started', 'trips', ['business_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trips_business_started', table_name='trips')
    op.drop_index('ix_trips_business_ended', table_name='trips')
    op.drop_index('ix_fuel_entries_business_captured', table_name='fuel_entries')
    op.drop_index('ix_expenses_business_spent', table_name='expenses')
    op.drop_index('ix_behaviour_driver_time', table_name='behaviour_events')
    op.drop_index('ix_audit_logs_business_created', table_name='audit_logs')
    # ### end Alembic commands ###
