"""partner programme

Revision ID: 0022
Revises: 0021
Create Date: 2026-10-04 07:16:05.513685

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0022'
down_revision: str | Sequence[str] | None = '0021'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=True),
    sa.Column('portal_key_hash', sa.String(length=64), nullable=True),
    sa.Column('commission_bp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_partners_portal_key_hash'), 'partners', ['portal_key_hash'], unique=False)
    op.create_index(op.f('ix_partners_status'), 'partners', ['status'], unique=False)
    op.create_table('partner_commissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('basis_cents', sa.BigInteger(), nullable=False),
    sa.Column('pct_bp', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('accrued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_reference', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['subscription_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_partner_commissions_partner_id'), 'partner_commissions', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_commissions_status'), 'partner_commissions', ['status'], unique=False)
    op.add_column('businesses', sa.Column('referred_by_partner_id', sa.Uuid(), nullable=True))
    op.add_column('businesses', sa.Column('referred_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_businesses_referred_by_partner_id'), 'businesses', ['referred_by_partner_id'], unique=False)
    op.create_foreign_key('fk_businesses_referred_by_partner', 'businesses', 'partners', ['referred_by_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_businesses_referred_by_partner', 'businesses', type_='foreignkey')
    op.drop_index(op.f('ix_businesses_referred_by_partner_id'), table_name='businesses')
    op.drop_column('businesses', 'referred_at')
    op.drop_column('businesses', 'referred_by_partner_id')
    op.drop_index(op.f('ix_partner_commissions_status'), table_name='partner_commissions')
    op.drop_index(op.f('ix_partner_commissions_partner_id'), table_name='partner_commissions')
    op.drop_table('partner_commissions')
    op.drop_index(op.f('ix_partners_status'), table_name='partners')
    op.drop_index(op.f('ix_partners_portal_key_hash'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
