"""usage counters

Revision ID: 0023
Revises: 0022
Create Date: 2026-10-04 07:28:35.582020

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0023'
down_revision: str | Sequence[str] | None = '0022'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_counters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('feature', sa.String(length=30), nullable=False),
    sa.Column('business_key', sa.String(length=16), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'feature', 'business_key')
    )
    op.create_index(op.f('ix_usage_counters_day'), 'usage_counters', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_counters_day'), table_name='usage_counters')
    op.drop_table('usage_counters')
    # ### end Alembic commands ###
