"""recurring work

Revision ID: 0024
Revises: 0023
Create Date: 2026-10-04 18:38:46.264527

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0024'
down_revision: str | Sequence[str] | None = '0023'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_job_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('cadence', sa.String(length=8), nullable=False),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('pickup_time', sa.Time(), nullable=False),
    sa.Column('deliver_within_hours', sa.Integer(), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_schedules_business_id'), 'job_schedules', ['business_id'], unique=False)
    op.create_index(op.f('ix_job_schedules_template_job_id'), 'job_schedules', ['template_job_id'], unique=False)
    op.create_table('job_schedule_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_on', sa.Date(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['job_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'occurrence_on')
    )
    op.create_index(op.f('ix_job_schedule_runs_business_id'), 'job_schedule_runs', ['business_id'], unique=False)
    op.create_index(op.f('ix_job_schedule_runs_schedule_id'), 'job_schedule_runs', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_schedule_runs_schedule_id'), table_name='job_schedule_runs')
    op.drop_index(op.f('ix_job_schedule_runs_business_id'), table_name='job_schedule_runs')
    op.drop_table('job_schedule_runs')
    op.drop_index(op.f('ix_job_schedules_template_job_id'), table_name='job_schedules')
    op.drop_index(op.f('ix_job_schedules_business_id'), table_name='job_schedules')
    op.drop_table('job_schedules')
    # ### end Alembic commands ###
