"""platform etims invoices

Revision ID: 0025
Revises: 0024
Create Date: 2026-10-04 19:31:10.061519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0025'
down_revision: Union[str, Sequence[str], None] = '0024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_etims_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_invoice_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('receipt_no', sa.String(length=40), nullable=True),
    sa.Column('sdc_id', sa.String(length=40), nullable=True),
    sa.Column('sdc_time', sa.String(length=20), nullable=True),
    sa.Column('receipt_signature', sa.String(length=200), nullable=True),
    sa.Column('internal_data', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_invoice_id'], ['subscription_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no'),
    sa.UniqueConstraint('subscription_invoice_id')
    )
    op.create_index(op.f('ix_platform_etims_submissions_business_id'), 'platform_etims_submissions', ['business_id'], unique=False)
    op.create_index(op.f('ix_platform_etims_submissions_next_attempt_at'), 'platform_etims_submissions', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_platform_etims_submissions_status'), 'platform_etims_submissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_etims_submissions_status'), table_name='platform_etims_submissions')
    op.drop_index(op.f('ix_platform_etims_submissions_next_attempt_at'), table_name='platform_etims_submissions')
    op.drop_index(op.f('ix_platform_etims_submissions_business_id'), table_name='platform_etims_submissions')
    op.drop_table('platform_etims_submissions')
    # ### end Alembic commands ###
