"""card payments

Revision ID: 0027
Revises: 0026
Create Date: 2026-10-04 21:04:10.329508

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0027'
down_revision: str | Sequence[str] | None = '0026'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_payments', sa.Column('method', sa.String(length=8), server_default='mpesa', nullable=False))
    op.alter_column('subscription_payments', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE subscription_payments SET phone = '' WHERE phone IS NULL")  # a card payment has no phone
    op.alter_column('subscription_payments', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('subscription_payments', 'method')
    # ### end Alembic commands ###
