"""platform console

Revision ID: 0028
Revises: 0027
Create Date: 2026-10-05 00:17:03.512315

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0028'
down_revision: str | Sequence[str] | None = '0027'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_actions_action'), 'platform_actions', ['action'], unique=False)
    op.create_index(op.f('ix_platform_actions_business_id'), 'platform_actions', ['business_id'], unique=False)
    op.create_index(op.f('ix_platform_actions_created_at'), 'platform_actions', ['created_at'], unique=False)
    op.create_table('platform_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_notes_business_id'), 'platform_notes', ['business_id'], unique=False)
    op.add_column('feedback', sa.Column('status', sa.String(length=10), server_default='new', nullable=False))
    op.add_column('feedback', sa.Column('handled_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('feedback', sa.Column('handled_note', sa.String(length=500), nullable=True))
    op.add_column('feedback', sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_foreign_key('fk_feedback_handled_by_user_id', 'feedback', 'users', ['handled_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_feedback_handled_by_user_id', 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_status'), table_name='feedback')
    op.drop_column('feedback', 'handled_at')
    op.drop_column('feedback', 'handled_note')
    op.drop_column('feedback', 'handled_by_user_id')
    op.drop_column('feedback', 'status')
    op.drop_index(op.f('ix_platform_notes_business_id'), table_name='platform_notes')
    op.drop_table('platform_notes')
    op.drop_index(op.f('ix_platform_actions_created_at'), table_name='platform_actions')
    op.drop_index(op.f('ix_platform_actions_business_id'), table_name='platform_actions')
    op.drop_index(op.f('ix_platform_actions_action'), table_name='platform_actions')
    op.drop_table('platform_actions')
    # ### end Alembic commands ###
